# Roles define special permissions users can promote themselves to under certain circumstances.
# There are two ways to get a role: either login as an authorized user, using the /manage command
# to get the permissions for the defined by `manager_role` in config.toml.

[[role]]
# The name of the role.
name = "Admin"

# The special permissions of the role.
# TODO: put a wiki link or something that explains each permission.
# Default: [].
permissions = ["all"]

[[role]]
name = "Moderator"

# Permissions can also be set negatively.
# To do so, start with "all" and add a "^" to permissions you'd like to unset.
permissions = ["all", "^mod_database", "^unban", "^reserved_names"]

[[role]]
# In this default configuration, this role is set as the `manager_role` in config.toml.
name = "Room Manager"

permissions = ["status", "lock", "description", "background", "ambiance"]

