# This file defines the configuration for each room. To add a room, type [[room]]
# and then list the room's attributes.

[[room]]
# The name of the room.
# Default value: "Unknown".
name = "Lobby"

# The description of the room.
# Default value: "".
description = "The lobby."

# The default background of the room.
# Default value: "".
background = "RV - Center Lobby"

# Whether to lock the background to the default. Makes it so special permissions are required to change it.
# If set to false, still requires users to have the Room Manager role or similar to change background.
# Default: false.
lock_background = true

# The default ambiance track of the room.
# Default value: "~stop.mp3".
ambiance = "~stop.mp3"

# Whether to lock the ambiance track to the default. Makes it so special permissions are required to change it.
# If set to false, still requires users to have the Room Manager role or similar to change ambiance.
# Default: false.
lock_ambiance = true

# Which character lists from `characters.toml` to include in the room's char list.
# If "all" is in the list, then it will use all of them.
# Default value: ["all"].
character_lists = ["all"]

# Which song categories from `music.toml` to include in the room's char list.
# If "all" is in the list, then it will use all of them.
# Default value: ["all"].
song_categories = ["all"]

# Which sides (or pos/positions) the client can pick in this room.
# Depending on the background, this can enjoy more than the default positions,
# as, if "pos" is in the list and not one of the defaults, the client will look for
# the images "pos" and "pos_overlay" for the background.
# Default: ["wit", "def", "pro", "jud", "hld", "hlp"]
side_list = ["wit", "def", "pro", "jud", "hld", "hlp"]

# Which rooms are adjacent to this one, i.e., that can be seen and accessed from this one.
# If "all" is in the list, then all rooms will considered adjacent.
#
# Note: adjacency is NOT necessarily symmetric. I.e., if Room A has Room B in its list but Room B
# does not have Room A in its list, then Room B will be accessible from Room A but Room A will not
# be accessible from Room B. Both need to have each other in their lists for the symmetry.
# Default value: [].
adjacent_rooms = ["Lounge", "Hub"]

# Whether to allow blankposting in this room.
# Default: true.
allow_blankpost = true

# Whether to allow shouting in this room.
# Default: true.
allow_shouting = true

# Whether to allow iniswapping in this room.
# Default: true.
allow_iniswapping = true

# Whether to force preanims to play immediately (i.e. preanims don't interrupt, and play at
# the same time as the message).
# Default: false.
force_immediate = false

# The methods which will be used for logging this room's events.
# Available methods are:
#    * "terminal" - will log to standard output (i.e. terminal).
#    * "file"     - will log to the file "log/room/room_name.log" in relation to the server executable.
#                 Beware: For the log file, the room name will be formatted in lower case and spaces will turn into underlines.
#                 Make sure no log file names collide, or different rooms may log to the same file.
# Default value: ["file"].
log_methods = ["terminal", "file"]

# Whether to log debugging messages. They tend to be very verbose/unnecessary for normal usage.
# Default value: false.
log_debug = true

[[room]]
name = "Lounge"
background = "RV - Therapist Office"
description = "The lounge."

character_lists = ["all"]
song_categories = ["all"]

adjacent_rooms = ["Lobby"]

log_methods = ["terminal", "file"]
log_debug = true

[[room]]
name = "Hub"
background = "RV - Top Floor Hallway"
description = "The Hub. Connects to other areas."

character_lists = ["all"]
song_categories = ["all"]

adjacent_rooms = [ "Lobby", "Ace Attorney", "Danganronpa", "Your Turn To Die",
                   "AA and DR", "DR and YTTD"]

log_methods = ["terminal", "file"]
log_debug = true

[[room]]
name = "Ace Attorney"
background = "gs4"
description = "Only Ace Attorney music and chars here."

character_lists = ["Ace Attorney"]
song_categories = ["Ace Attorney"]

adjacent_rooms = ["Hub", "AA and DR"]

log_methods = ["terminal", "file"]
log_debug = true

[[room]]
name = "Danganronpa"
background = "V3 Trial"
description = "Only Danganronpa music and chars here."

character_lists = ["Danganronpa"]
song_categories = ["Danganronpa"]

adjacent_rooms = ["Hub", "AA and DR", "DR and YTTD"]

log_methods = ["terminal", "file"]
log_debug = true

[[room]]
name = "Your Turn To Die"
background = "Trial 2"
description = "Only YTTD music and chars here."

character_lists = ["Your Turn To Die"]
song_categories = ["Your Turn To Die"]

adjacent_rooms = ["Hub", "DR and YTTD"]

log_methods = ["terminal", "file"]
log_debug = true

[[room]]
name = "AA and DR"
background = "gs4"
description = "AA and DR music and chars here."

character_lists = ["Ace Attorney", "Danganronpa"]
song_categories = ["Ace Attorney", "Danganronpa"]

adjacent_rooms = ["Hub", "Ace Attorney", "Danganronpa"]

log_methods = ["terminal", "file"]
log_debug = true

[[room]]
name = "DR and YTTD"
background = "V3 Trial"
description = "DR and YTTD music and chars here."

character_lists = ["Danganronpa", "Your Turn To Die"]
song_categories = ["Danganronpa", "Your Turn To Die"]

adjacent_rooms = ["Hub", "Danganronpa", "Your Turn To Die"]

log_methods = ["terminal", "file"]
log_debug = true
