name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build server
      shell: bash
      run: make server

    - name: Build serverctl
      shell: bash
      run: make serverctl

    # TODO: testing
    # - name: Test
    #  run: go test -v ./...

