name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        sqlite: [static, shared]
        exclude:
          - os: windows-latest
            sqlite: shared
      
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build server
      env:
        SUFFIX: ${{ matrix.sqlite == 'static' && '-static' || ''}}
      shell: bash
      run: CGO_ENABLED=1 make server$SUFFIX

    - name: Build serverctl
      shell: bash
      run: CGO_ENABLED=1 make serverctl

    - name: Copy sqlite dylib (Mac Shared)
      shell: bash
      if: matrix.os == 'macos-latest' && matrix.sqlite == 'shared'
      run: cp /opt/homebrew/opt/sqlite/lib/libsqlite3.0.dylib bin

    - name: Copy sample config
      shell: bash
      run: mv bin/config_sample bin/config

    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: scs-${{ matrix.os }}-${{ matrix.sqlite }}
        path: ${{ github.workspace }}/bin/

    # TODO: testing
    # - name: Test
    #  run: go test -v ./...

